version: '3.4'

services:
  housefinder_api:
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro

  apigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"
    depends_on:
      - housefinder_api